name: shoppinglistapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  sqflite: ^1.3.1
  provider: ^4.3.2
  intl: ^0.16.1
  toast: ^0.1.5
  progress_indicators: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:


  uses-material-design: true
  assets:
    - images/mericartlogo.png
  fonts:
    - family: 'Ubuntu'
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
    - family: 'Signatra'
      fonts:
        - asset: fonts/Signatra.ttf
